const ASSISTANT_CONVERSATION_SUBSCRIBE = "assistant.conversation.subscribe";
const ASSISTANT_CONVERSATION_UNSUBSCRIBE = "assistant.conversation.unsubscribe";
const ASSISTANT_CONVERSATION_EVENT = "assistant.conversation.event";

export {
  ASSISTANT_CONVERSATION_SUBSCRIBE,
  ASSISTANT_CONVERSATION_UNSUBSCRIBE,
  ASSISTANT_CONVERSATION_EVENT
};
