const ASSISTANT_CONVERSATIONS_REPOSITORY_TOKEN = "assistant.conversation.repository";
const ASSISTANT_MESSAGES_REPOSITORY_TOKEN = "assistant.message.repository";
const ASSISTANT_SETTINGS_REPOSITORY_TOKEN = "assistant.settings.repository";
const ASSISTANT_TRANSCRIPT_SERVICE_TOKEN = "assistant.transcript.service";
const ASSISTANT_CHAT_SERVICE_TOKEN = "assistant.chat.service";
const ASSISTANT_SETTINGS_SERVICE_TOKEN = "assistant.settings.service";
const ASSISTANT_AI_CLIENT_TOKEN = "assistant.ai.client";
const ASSISTANT_SERVICE_TOOL_CATALOG_TOKEN = "assistant.service.tool-catalog";

export {
  ASSISTANT_CONVERSATIONS_REPOSITORY_TOKEN,
  ASSISTANT_MESSAGES_REPOSITORY_TOKEN,
  ASSISTANT_SETTINGS_REPOSITORY_TOKEN,
  ASSISTANT_TRANSCRIPT_SERVICE_TOKEN,
  ASSISTANT_CHAT_SERVICE_TOKEN,
  ASSISTANT_SETTINGS_SERVICE_TOKEN,
  ASSISTANT_AI_CLIENT_TOKEN,
  ASSISTANT_SERVICE_TOOL_CATALOG_TOKEN
};
