#!/usr/bin/env bash
set -euo pipefail

APP_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

require_command() {
  local name="$1"
  if ! command -v "$name" >/dev/null 2>&1; then
    echo "[release] required command not found: $name" >&2
    exit 1
  fi
}

ensure_clean_worktree() {
  if [[ -n "$(git status --porcelain)" ]]; then
    echo "[release] worktree is not clean. Commit/stash first." >&2
    exit 1
  fi
}

ensure_on_main() {
  local current_branch
  current_branch="$(git rev-parse --abbrev-ref HEAD)"
  if [[ "$current_branch" != "main" ]]; then
    echo "[release] current branch is \"$current_branch\". Switch to main first." >&2
    exit 1
  fi
}

main() {
  require_command git
  require_command npm
  require_command gh

  cd "$APP_ROOT"

  if ! gh auth status >/dev/null 2>&1; then
    echo "[release] gh is not authenticated. Run: gh auth login" >&2
    exit 1
  fi

  ensure_clean_worktree
  ensure_on_main

  echo "[release] syncing local main..."
  git fetch origin main
  git pull --ff-only origin main

  echo "[release] running package refresh..."
  npm run jskit:update

  if [[ -z "$(git status --porcelain)" ]]; then
    echo "[release] no changes produced by jskit:update. Nothing to release."
    exit 0
  fi

  local timestamp
  local pretty_time
  local branch
  local commit_message
  local pr_title
  local pr_url

  timestamp="$(date -u +%Y%m%d-%H%M%S)"
  pretty_time="$(date -u +'%Y-%m-%d %H:%M UTC')"
  branch="release/${timestamp}"
  commit_message="chore: release ${pretty_time}"
  pr_title="Release ${pretty_time}"

  echo "[release] creating branch ${branch}..."
  git checkout -b "$branch"

  git add -A
  git commit -m "$commit_message"
  git push -u origin "$branch"

  pr_url="$(
    gh pr create \
      --base main \
      --head "$branch" \
      --title "$pr_title" \
      --body "Automated release commit generated by \`npm run release\`."
  )"

  echo "[release] created PR: $pr_url"
  gh pr merge "$pr_url" --merge --delete-branch

  echo "[release] merged. syncing local main..."
  git checkout main
  git pull --ff-only origin main

  echo "[release] done."
}

main "$@"
