import * as billingConstants from "@jskit-ai/billing-core/constants";

export const BILLING_PROVIDER_STRIPE = billingConstants.BILLING_PROVIDER_STRIPE;
export const BILLING_PROVIDER_PADDLE = billingConstants.BILLING_PROVIDER_PADDLE;
export const BILLING_DEFAULT_PROVIDER = billingConstants.BILLING_DEFAULT_PROVIDER;
export const BILLING_ACTIONS = billingConstants.BILLING_ACTIONS;
export const BILLING_FAILURE_CODES = billingConstants.BILLING_FAILURE_CODES;
export const BILLING_IDEMPOTENCY_STATUS = billingConstants.BILLING_IDEMPOTENCY_STATUS;
export const BILLING_SUBSCRIPTION_STATUS = billingConstants.BILLING_SUBSCRIPTION_STATUS;
export const NON_TERMINAL_CURRENT_SUBSCRIPTION_STATUS_SET =
  billingConstants.NON_TERMINAL_CURRENT_SUBSCRIPTION_STATUS_SET;
export const TERMINAL_SUBSCRIPTION_STATUS_SET = billingConstants.TERMINAL_SUBSCRIPTION_STATUS_SET;
export const BILLING_CHECKOUT_SESSION_STATUS = billingConstants.BILLING_CHECKOUT_SESSION_STATUS;
export const CHECKOUT_BLOCKING_STATUS_SET = billingConstants.CHECKOUT_BLOCKING_STATUS_SET;
export const CHECKOUT_TERMINAL_STATUS_SET = billingConstants.CHECKOUT_TERMINAL_STATUS_SET;
export const CHECKOUT_STATUS_TRANSITIONS = billingConstants.CHECKOUT_STATUS_TRANSITIONS;
export const BILLING_RUNTIME_DEFAULTS = billingConstants.BILLING_RUNTIME_DEFAULTS;
export const BILLING_PROVIDER_REQUEST_SCHEMA_VERSION_BY_PROVIDER =
  billingConstants.BILLING_PROVIDER_REQUEST_SCHEMA_VERSION_BY_PROVIDER;
export const BILLING_PROVIDER_SDK_NAME_BY_PROVIDER = billingConstants.BILLING_PROVIDER_SDK_NAME_BY_PROVIDER;
export const LOCK_ORDER = billingConstants.LOCK_ORDER;
export const isBlockingCheckoutStatus = billingConstants.isBlockingCheckoutStatus;
export const isCheckoutTerminalStatus = billingConstants.isCheckoutTerminalStatus;
export const canTransitionCheckoutStatus = billingConstants.canTransitionCheckoutStatus;
export const statusFromFailureCode = billingConstants.statusFromFailureCode;
export const resolveProviderRequestSchemaVersion = billingConstants.resolveProviderRequestSchemaVersion;
export const resolveProviderSdkName = billingConstants.resolveProviderSdkName;
