import { createSchema } from "json-rest-schema";

const lightspeedDefinition = Object.freeze({
  id: "lightspeed", name: "Lightspeed", description: "Read products, inventory, sales, customers and outlets from a Lightspeed Retail X-Series store.",
  accountModes: ["shared", "per-user", "assistant"], authenticationMethods: ["oauth2"],
  oauthClientAuthenticationMethods: ["client_secret_post"],
  settingsSchema: createSchema({
    domainPrefix: { type: "string", required: true, minLength: 1, maxLength: 63,
      validator: (value) => /^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/u.test(value) || "Enter the lowercase store prefix without a URL, dots or spaces." }
  }),
  settingsFields: [{ name: "domainPrefix", label: "Domain prefix", placeholder: "your-store",
    hint: "The store prefix from https://your-store.retail.lightspeed.app. Use the store you intend to authorize." }],
  scopes: [
    { value: "retailer:read", label: "Read retailer settings", recommended: true },
    { value: "outlets:read", label: "Read outlets", recommended: true },
    { value: "registers:read", label: "Read registers", recommended: true },
    { value: "payment_types:read", label: "Read payment types", recommended: true },
    { value: "products:read", label: "Read products", recommended: true },
    { value: "products:read:price_books", label: "Read price books", recommended: true },
    { value: "inventory:read", label: "Read inventory", recommended: true },
    { value: "customers:read", label: "Read customers", recommended: true },
    { value: "sales:read", label: "Read sales", recommended: true },
    { value: "fulfillments:read", label: "Read fulfillments", recommended: true },
    { value: "promotions:read", label: "Read promotions", recommended: true },
    { value: "gift_cards:read", label: "Read gift cards", recommended: true },
    { value: "store_credits:read", label: "Read store credits", recommended: true },
    { value: "suppliers:read", label: "Read suppliers", recommended: true },
    { value: "taxes:read", label: "Read taxes", recommended: true },
    { value: "users:read", label: "Read users", recommended: true },
    { value: "audit:read", label: "Read audit events" },
    { value: "business_rules:read", label: "Read business rules" },
    { value: "business_rules:write", label: "Edit business rules" },
    { value: "channels:read", label: "Read channels" },
    { value: "consignments:read", label: "Read consignments" },
    { value: "consignments:write:inventory_count", label: "Perform inventory counts" },
    { value: "consignments:write:stock_order", label: "Process stock orders" },
    { value: "consignments:write:stock_transfer", label: "Transfer stock" },
    { value: "customers:write", label: "Edit customers" },
    { value: "custom_fields:read", label: "Read custom fields" },
    { value: "custom_fields:write", label: "Edit custom fields" },
    { value: "fulfillments:write", label: "Edit fulfillments" },
    { value: "gift_cards:write:issue", label: "Issue gift cards" },
    { value: "gift_cards:write:redeem", label: "Redeem gift cards" },
    { value: "inventory:write", label: "Edit inventory" },
    { value: "payments:read", label: "Read payments" },
    { value: "products:write", label: "Edit products" },
    { value: "products:write:price_books", label: "Edit price books" },
    { value: "promotions:write", label: "Edit promotions" },
    { value: "register:close", label: "Close registers" },
    { value: "register:open", label: "Open registers" },
    { value: "remote_rules:read", label: "Read remote rules" },
    { value: "remote_rules:write", label: "Edit remote rules" },
    { value: "sales:write", label: "Edit sales" },
    { value: "serial_numbers:read", label: "Read serial numbers" },
    { value: "serial_numbers:write", label: "Edit serial numbers" },
    { value: "services:read", label: "Read services" },
    { value: "services:write", label: "Edit services" },
    { value: "store_credits:write:issue", label: "Issue store credits" },
    { value: "suppliers:write", label: "Edit suppliers" },
    { value: "taxes:write", label: "Edit taxes" },
    { value: "users:write", label: "Edit users" },
    { value: "webhooks", label: "Manage application webhooks" }
  ],
  setup: { url: "https://x-series-api.lightspeedhq.com/docs/authorization", steps: [
    "Open developers.retail.lightspeed.app and register a developer account; your retail-store login is separate. Open Applications > Create and register this application's exact Suggested callback URL as its redirect URI.",
    "Copy Client ID here and Save configuration. Choose Set credential in Env to store Client Secret under the displayed reference. Choose Set callback in Env and save the exact registered URL. Your application backend must implement that callback.",
    "From https://your-store.retail.lightspeed.app, enter only your-store in Domain prefix. This slot connects that store; a callback from another store cannot change the credential destination. Use a separate configuration slot for another store.",
    "Keep products:read for verification and select only the other permissions your application needs. Extra permissions do not add runtime operations. Save configuration, then Connect account for shared access. Each-user access connects from the generated application's account screen after its own login.",
    "Approve the intended retailer in Lightspeed. Verification reads a product page without changing stock or customer data. If declined consent leaves the screen waiting, choose Cancel connection before trying again. Disconnect removes the local grant, not provider authorization.",
    "Select inventory:read to read stock and sales:read for sales pages, then reconnect if permissions changed. Inventory returns flat rows with current_inventory_level and quantity_to_procure; the app must interpret those separately rather than treating procure quantity as negative stock. Use explicit version pages; no automatic stock sync is installed.",
    "The app can build a low-stock or sales dashboard from these reads. Customer/product edits, stock adjustments, sale/payment writes, gift-card/store-credit workflows, webhook processing and editor-assistant attachment are not implemented here. Selecting an advanced write scope alone does not add those operations.",
    "Unapproved registrations can connect up to 30 stores; production-ready public applications require Lightspeed approval. This connector is Retail X-Series only. R-Series, K-Series and personal-token setup are not supported here. Changing the callback, client or store can require reconnection."
  ] }
});
export { lightspeedDefinition };
