import { createSchema } from "json-rest-schema";
import { secretReference } from "@jskit-ai/connectors-core/shared/configuration";

const semrushDefinition = Object.freeze({
  id: "semrush", name: "Semrush", description: "Read keyword and backlink reports and manage Semrush projects using a V4 API key.",
  accountModes: ["shared", "assistant"], authenticationMethods: ["api-key"], scopes: [],
  settingsSchema: createSchema({ v3ApiKeyRef: { ...secretReference, required: false } }),
  settingsFields: [{ name: "v3ApiKeyRef", label: "V3 API key reference (optional)", placeholder: "env:SEMRUSH_V3_KEY",
    environmentCredential: { label: "Semrush V3 API key", public: false },
    hint: "For domain overview and domain/URL/subfolder keyword reports and position tracking: My profile > API Keys > copy your Version 3 key into this project's Env. Leave empty if only using V4 reports/projects." }],
  apiKeyReferenceLabel: "V4 API key reference",
  apiKeyReferenceHint: "Use a new Semrush V4 key: Read-only for reports and project reads, Read and write for creating, renaming or deleting projects. V3 keys and OAuth tokens are different credentials.",
  setup: { url: "https://developer.semrush.com/api/v4/get-started/quick-start/", steps: [
    "Open the profile icon in Semrush, then My profile > API Keys > + Create API key.",
    "Create a V4 key for this application. Select Read-only for reports and project reads, or Read and write if the app creates, renames or deletes projects; choose an expiry. Projects access requires SEO Business and available API units.",
    "Copy the key into Env when it is shown and save only its reference here. This flow needs no Client ID, secret or callback URL.",
    "The runtime verifies project access. OWN is the default list scope; ALL, SHARED and CORPORATE are explicit operation inputs.",
    "Keyword metrics and backlink overview, links, referring domains and anchors use this V4 key. These Early Access reports consume account API units only when the app requests them; connecting verifies projects, not every report entitlement.",
    "Project deletion permanently removes the project, tools, settings and history. The generated app must confirm and authorize this action. Disconnecting here only removes local connection state.",
    "For domain overview and organic/paid keyword reports for domains, URLs and subfolders, open My profile > API Keys and copy the autogenerated Version 3 key into Env using the optional V3 reference. It is sent only to Semrush for V3 reports. Do not paste it into the V4 field. Position tracking uses this V3 key too: discover campaigns from the project ID, then use the returned campaign ID for dates and ranking reports. Existing campaigns and harvested data are required. OAuth remains unimplemented.",
    "Separate keys on one account share account capacity. This initial runtime does not implement the captured OAuth connection or individual app-user login."
  ] }
});
export { semrushDefinition };
