const waveDefinition = Object.freeze({
  id: "wave", name: "Wave", description: "Connect project-owned Wave accounts for customers, products, invoices, estimates and accounting workflows.",
  accountModes: ["shared", "per-user", "assistant"], authenticationMethods: ["oauth2"],
  oauthClientAuthenticationMethods: ["client_secret_post"],
  scopes: [
    { value: "user:read", label: "Read the connected user's profile", recommended: true },
    { value: "business:read", label: "Read businesses", recommended: true },
    { value: "customer:read", label: "Read customers", recommended: true },
    { value: "invoice:read", label: "Read invoices", recommended: true },
    { value: "user:*", label: "Full user access" },
    { value: "business:write", label: "Edit businesses" },
    { value: "business:*", label: "Full business access" },
    { value: "account:read", label: "Read accounting accounts" },
    { value: "account:write", label: "Edit accounting accounts" },
    { value: "account:*", label: "Full accounting account access" },
    { value: "customer:write", label: "Edit customers" },
    { value: "customer:*", label: "Full customer access" },
    { value: "estimate:read", label: "Read estimates" },
    { value: "estimate:write", label: "Edit estimates" },
    { value: "estimate:send", label: "Send estimates" },
    { value: "estimate:*", label: "Full estimate access" },
    { value: "invoice:write", label: "Edit invoices" },
    { value: "invoice:send", label: "Send invoices" },
    { value: "invoice:*", label: "Full invoice access" },
    { value: "product:read", label: "Read products and services" },
    { value: "product:write", label: "Edit products and services" },
    { value: "product:*", label: "Full product and service access" },
    { value: "sales_tax:read", label: "Read sales taxes" },
    { value: "sales_tax:write", label: "Edit sales taxes" },
    { value: "sales_tax:*", label: "Full sales tax access" },
    { value: "transaction:write", label: "Create money transactions" },
    { value: "transaction:*", label: "Full transaction access" },
    { value: "vendor:read", label: "Read vendors" },
    { value: "vendor:write", label: "Edit vendors" },
    { value: "vendor:*", label: "Full vendor access" },
    { value: "checkout:read", label: "Read checkouts" },
    { value: "checkout:*", label: "Full checkout access" }
  ],
  setup: { url: "https://developer.waveapps.com/hc/en-us/articles/50682251860884-2-Create-an-application", steps: [
    "Sign in to Wave, open Manage applications in the developer portal, and choose Create New Application. Enter your application name and its backend Redirect URI, then save the application.",
    "Use this project's deployed application URL as the callback origin, followed by the callback route implemented by its backend. Register that exact URL in Wave; do not use the Vibe64 editor address.",
    "Copy the issued Client ID into Client ID. Put the issued Client Secret in the project's Env, then enter its env:VARIABLE reference in Client secret reference. A personal access token is not a Client Secret.",
    "Put the same registered callback URL in the project's Env and enter its env:VARIABLE reference in Callback URL reference. The backend must serve that route and use the same callback during token refresh.",
    "Wave OAuth access requires an active Pro or Wave Advisor business subscription. Integrations for other Wave users require Wave approval.",
    "Keep profile and business read access for connection verification and business selection. Enable read permissions for records you use; add write permissions only for editing, and invoice/estimate send only when the app sends those documents. Write does not imply read.",
    "Product writes that reference accounts or taxes need those read permissions too. Transaction creation needs transaction write and read access to its referenced accounts, customers and taxes. Wildcard permissions include the corresponding reads and writes.",
    "Save the configuration, then use the project's Connect action to authorize the intended Wave account. Select and authorize a business from the returned list inside your app; connecting a profile does not sign someone into your app or select the first business automatically.",
    "Reconnect after changing permissions, the Client ID or callback URL. When moving to a custom domain, update Wave's registered redirect and the project's callback Env value together. Keep the project's private token store when moving hosting.",
    "Disconnect currently deletes the local connection. Remove the grant separately in Wave if you also want provider-side revocation. Vendor access is read-only in this runtime: the reviewed public API exposes no vendor create/update mutations. Extra scope choices do not add missing operations."
  ] }
});
export { waveDefinition };
