import { createSchema } from "json-rest-schema";

const wixDefinition = Object.freeze({
  id: "wix", name: "Wix", description: "Use project-owned Wix account and site API access.",
  accountModes: ["shared", "assistant"], authenticationMethods: ["api-key"], scopes: [],
  settingsSchema: createSchema({ accountId: { type: "string", required: true, minLength: 36, maxLength: 36,
    validator: (value) => /^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/iu.test(value) || "Enter the Account ID from Wix's API Keys Manager." },
    selectableSiteIds: { type: "string", maxLength: 4000, validator: value => {
      const ids = value.split(",").map(id => id.trim());
      return ids.length <= 100 && ids.every(id => /^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/iu.test(id)) && new Set(ids.map(id => id.toLowerCase())).size === ids.length || "Enter up to 100 distinct Site IDs separated by commas.";
    } },
    siteId: { type: "string", minLength: 36, maxLength: 36, validator: value => /^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/iu.test(value) || "Copy the Site ID from the Wix site dashboard URL." } }),
  settingsFields: [{ name: "accountId", label: "Account ID", placeholder: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    hint: "Copy your account's ID from the API Keys Manager. A site ID is a different setting." },
    { name: "selectableSiteIds", label: "Selectable Site IDs", placeholder: "Site ID, Site ID", hint: "Optional. Comma-separated sites the app may explicitly select. The app must still authorize each user's site access. Leave empty for a fixed-site connection." },
    { name: "siteId", label: "Site ID", placeholder: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", hint: "Required for site operations. Copy the ID after /dashboard/ in the intended Wix site dashboard URL." }],
  setup: {
    url: "https://dev.wix.com/docs/go-headless/authentication/admin/generate-an-api-key",
    steps: [
      "Sign into the intended Wix account as an owner or co-owner and open its API Keys Manager in account settings.",
      "Generate an API key, give it a name and grant Read Site Data. Complete the requested account verification and copy the token into your backend Env.",
      "Copy the Account ID from the same manager. Enter it here with the API key reference; never paste the token into source.",
      "Save the configuration, supply the referenced key in the project backend Env, then choose Check connection and Connect account. Account verification queries sites; an empty list is valid and does not prove permissions for site operations. No OAuth app or callback URL is needed.",
      "To rotate a key, create a replacement in Wix with the required permissions, update the referenced backend Env value, then Check connection and Reconnect. Verify the intended site operation before retiring the old key in Wix. Disconnect removes local application access; it does not revoke the Wix key.",
      "For a multi-site app, list the account sites, then enter only approved IDs in Selectable Site IDs. The app may pass one of these as siteId on a site operation. Your backend must authorize the user's site choice before invoking it. Omitted siteId uses the fixed Site ID; requests cannot select an unlisted site. Changing the allowed sites requires verification again.",
      "For CRM access, enter the intended Site ID from its dashboard URL (after /dashboard/) and grant Read Contacts, plus Manage Contacts for contact creation and updates. Restrict the key to the sites the project needs. Changing the site requires verification again.",
      "For Wix-hosted checkout, edit the project’s API key in Wix Account Settings > API Keys: grant Write Carts V2 (PII) to create carts and Read Carts V2 (PII) to retrieve checkout URLs. Publish the Wix site and configure its payment methods. Your app owns customer/cart authorization and redirects to Wix; a checkout URL does not prove payment.",
      "For booking services, enable Wix Bookings on the selected site and grant Read Bookings - Public Data; edits also need Manage Bookings. Fetch the current service revision before changing it. Service creation also needs explicit online-booking, capacity and payment settings. Your app can query categories and staff with Read Bookings - Public Data. Retrieve service variants before presenting price or duration choices; keep the option IDs and participant selections in your app. Retrieve add-on groups too, show their prompts and enforce their selection limits. Pass the selected duration/add-ons when checking appointment availability and the selected participant choices/add-ons when creating the booking. For appointments, select the returned staff resourceId (not staff id) and duration; select a service category to make it visible on the Wix site. Create class/course sessions separately.",
      "For appointment and class availability, grant the Time Slots read permission (BOOKINGS.AVAILABILITY_READ_TIME_SLOTS). Your app must pass the intended time zone, let the customer choose a slot and recheck it before creating a booking; viewing a slot does not reserve it. For classes, filter by party size and recheck the selected eventInfo.eventId before booking. For appointments, recheck the selected resource and location; availability uses BUSINESS/CUSTOM where booking creation uses OWNER_BUSINESS/OWNER_CUSTOM.",
      "For booking creation, grant Manage Bookings. Grant Get Form Summary (forms:v4:form:get_form_summary) for form discovery. Your app reads the service form ID, retrieves its fields, uses their exact targets, recheck capacity and handle the returned booking status. Creation is not payment or confirmation. Participant notifications and SMS reminders are opt-in in this connector.",
      "Read bookings with the corresponding Read Bookings permission, or Manage Bookings for the administrative workflow. Query the exact booking to get its current revision and allowed actions before canceling. Cancellation requires Manage Bookings. Your app must authorize the action; choose participant notification explicitly. Waiving charges can cancel an eligible unpaid Wix order and is not a refund. For rescheduling, check the booking’s allowed actions and current revision, then select and recheck a new appointment slot or class event. Courses cannot be rescheduled. Booking policy overrides are not enabled. For a custom checkout, your app can explicitly confirm or decline with Manage Bookings; direct confirmation skips availability checks. With Wix eCommerce checkout, let Wix manage confirmation. Your app must verify payment status on its backend.",
      "For CMS collection browsing, grant Manage Data Collections on the intended site. Your app lists collections and reads their field metadata; grant Read Data Items to browse collection content too. These browse operations do not change the schema or content. For content editing, add the permission identified as WIX_DATA.PATCH in Wix’s Patch Data Item documentation to the API key permissions. The app reads the item then explicitly patches selected fields; use a condition for conflicting edits and check the outcome before retrying. Collection IDs can include an app prefix such as AppName/CollectionName. Keep administrative collection metadata behind app authorization.",
      "For business-location selection, grant Read Locations. Query locations for the configured Site ID to obtain booking location IDs, addresses and time zones. The app queries only authorized locations and excludes archived locations by default; selecting a location does not reserve a booking. To create or update locations, add Manage Locations to the key permissions. Updates replace the full writable location: read it first, retain every field you need and send its exact revision. Location business hours are not a Wix Bookings schedule.",
      "For products, install Wix Stores on the intended site and grant Read v3 catalog (PII) for version discovery. The app must check whether the site uses V1_CATALOG or V3_CATALOG before selecting product APIs; these catalogues are not interchangeable. Grant Read Products for V1 or Read products in v3 catalog for V3. V1 name, visibility and base-price edits also require Manage Products; prices use the site currency, and this endpoint has no revision guard. V3 product lists omit variants; fetch the individual product for those details. To rename or change visibility in V3, also grant Product write in v3 catalog and pass the current product revision. A revision conflict requires re-reading and reviewing the change; do not automatically retry. Hiding a product without options also hides its default variant.",
      "For commerce order reads, grant Read Orders on the selected site. Your app must authorize each customer's order access. Order search omits PENDING and REJECTED unless requested explicitly, and never lists INITIALIZED orders; retrieve those by known order ID. Use orderFulfillments.list with the authorized order ID to read shipped quantities and tracking details; an empty list means no recorded fulfillments. To create shipments or update tracking, grant Manage Orders. Select explicit order line-item quantities; creation requires an APPROVED order. Wix may send shipping emails according to site settings. Inspect existing fulfillments before repeating any uncertain write. Fulfillment handling status is distinct from order payment status. Reading an order does not collect payment.",
      "This account credential is for backend administrative operations. It does not connect each app user's Wix account or implement application login."
    ]
  }
});
export { wixDefinition };
