export {
  DEFAULT_IMAGE_COMPRESSOR_OPTIONS,
  DEFAULT_IMAGE_DASHBOARD_OPTIONS,
  DEFAULT_IMAGE_EDITOR_OPTIONS,
  DEFAULT_IMAGE_UPLOAD_ALLOWED_MIME_TYPES,
  DEFAULT_IMAGE_UPLOAD_MAX_BYTES
} from "./imageUploadDefaults.js";
