const AUTH_POLICY_PUBLIC = "public";
const AUTH_POLICY_AUTHENTICATED = "authenticated";
const ROUTE_VISIBILITY_PUBLIC = AUTH_POLICY_PUBLIC;
const ROUTE_VISIBILITY_USER = "user";

export {
  AUTH_POLICY_PUBLIC,
  AUTH_POLICY_AUTHENTICATED,
  ROUTE_VISIBILITY_PUBLIC,
  ROUTE_VISIBILITY_USER
};
