// This file is generated by scripts/framework/generate-fastify-route-indexes.mjs.
export { createController } from "./controller.js";
export { buildRoutes } from "./routes.js";
export { schema } from "./schema.js";
