function createCommandHandlerDeps(deps = {}) {
  return {
    createCliError: deps.createCliError,
    createColorFormatter: deps.createColorFormatter,
    resolveWrapWidth: deps.resolveWrapWidth,
    writeWrappedItems: deps.writeWrappedItems,
    normalizeRelativePath: deps.normalizeRelativePath,
    normalizeRelativePosixPath: deps.normalizeRelativePosixPath,
    resolveAppRootFromCwd: deps.resolveAppRootFromCwd,
    loadLockFile: deps.loadLockFile,
    loadPackageRegistry: deps.loadPackageRegistry,
    loadBundleRegistry: deps.loadBundleRegistry,
    loadAppLocalPackageRegistry: deps.loadAppLocalPackageRegistry,
    mergePackageRegistries: deps.mergePackageRegistries,
    resolvePackageIdInput: deps.resolvePackageIdInput,
    resolveInstalledPackageIdInput: deps.resolveInstalledPackageIdInput,
    resolveInstalledNodeModulePackageEntry: deps.resolveInstalledNodeModulePackageEntry,
    hydratePackageRegistryFromInstalledNodeModules: deps.hydratePackageRegistryFromInstalledNodeModules,
    resolvePackageTemplateRoot: deps.resolvePackageTemplateRoot,
    validateInlineOptionsForPackage: deps.validateInlineOptionsForPackage,
    resolveLocalDependencyOrder: deps.resolveLocalDependencyOrder,
    validatePlannedCapabilityClosure: deps.validatePlannedCapabilityClosure,
    resolvePackageOptions: deps.resolvePackageOptions,
    applyPackageInstall: deps.applyPackageInstall,
    applyPackageMigrationsOnly: deps.applyPackageMigrationsOnly,
    applyPackagePositioning: deps.applyPackagePositioning,
    adoptAppLocalPackageDependencies: deps.adoptAppLocalPackageDependencies,
    loadAppPackageJson: deps.loadAppPackageJson,
    resolveLocalPackageId: deps.resolveLocalPackageId,
    createLocalPackageScaffoldFiles: deps.createLocalPackageScaffoldFiles,
    fileExists: deps.fileExists,
    applyPackageJsonField: deps.applyPackageJsonField,
    toFileDependencySpecifier: deps.toFileDependencySpecifier,
    writeJsonFile: deps.writeJsonFile,
    writeFile: deps.writeFile,
    mkdir: deps.mkdir,
    path: deps.path,
    inspectPackageOfferings: deps.inspectPackageOfferings,
    buildFileWriteGroups: deps.buildFileWriteGroups,
    listDeclaredCapabilities: deps.listDeclaredCapabilities,
    buildCapabilityDetailsForPackage: deps.buildCapabilityDetailsForPackage,
    formatPackageSubpathImport: deps.formatPackageSubpathImport,
    normalizePlacementOutlets: deps.normalizePlacementOutlets,
    normalizePlacementContributions: deps.normalizePlacementContributions,
    shouldShowPackageExportTarget: deps.shouldShowPackageExportTarget,
    classifyExportedSymbols: deps.classifyExportedSymbols,
    deriveProviderDisplayName: deps.deriveProviderDisplayName,
    restorePackageJsonField: deps.restorePackageJsonField,
    readFileBufferIfExists: deps.readFileBufferIfExists,
    removeEnvValue: deps.removeEnvValue,
    removeManagedViteProxyEntries: deps.removeManagedViteProxyEntries,
    hashBuffer: deps.hashBuffer,
    rm: deps.rm,
    discoverShellOutletTargetsFromApp: deps.discoverShellOutletTargetsFromApp
  };
}

export { createCommandHandlerDeps };
