<script setup>
const componentImport = "@jskit-ai/members-admin-client-element";
const componentSymbol = "MembersAdminClientElement";
</script>

<template>
  <section class="feature-page">
    <h1>Members</h1>
    <p>This page was generated by <code>@jskit-ai/members-admin-client-element</code>.</p>
    <p>
      Wire members runtime/composable, then render
      <code>{{ componentSymbol }}</code> from <code>{{ componentImport }}</code>.
    </p>
  </section>
</template>

<style scoped>
.feature-page {
  display: grid;
  gap: 0.5rem;
}

h1 {
  margin: 0;
  font-size: 1.5rem;
}

p {
  margin: 0;
  color: #4b5563;
}
</style>
