const ACCOUNT_SETTINGS_CHANGED_EVENT = "account.settings.changed";
const CONSOLE_SETTINGS_CHANGED_EVENT = "console.settings.changed";
const WORKSPACE_SETTINGS_CHANGED_EVENT = "workspace.settings.changed";
const WORKSPACE_MEMBERS_CHANGED_EVENT = "workspace.members.changed";
const WORKSPACE_INVITES_CHANGED_EVENT = "workspace.invites.changed";
const WORKSPACES_CHANGED_EVENT = "workspaces.changed";
const WORKSPACE_PENDING_INVITATIONS_CHANGED_EVENT = "workspace.invitations.pending.changed";

export {
  ACCOUNT_SETTINGS_CHANGED_EVENT,
  CONSOLE_SETTINGS_CHANGED_EVENT,
  WORKSPACE_SETTINGS_CHANGED_EVENT,
  WORKSPACE_MEMBERS_CHANGED_EVENT,
  WORKSPACE_INVITES_CHANGED_EVENT,
  WORKSPACES_CHANGED_EVENT,
  WORKSPACE_PENDING_INVITATIONS_CHANGED_EVENT
};
