import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

test("the JSKIT skill routes existing-app ports to the distributed migration guide", async () => {
  const skill = await readFile(path.join(packageRoot, "skills/jskit/SKILL.md"), "utf8");
  const sourceGuide = await readFile(
    path.join(packageRoot, "site/guide/app-setup/existing-application-migration.md"),
    "utf8"
  );
  const distributedGuide = await readFile(
    path.join(packageRoot, "guide/agent/app-setup/existing-application-migration.md"),
    "utf8"
  );

  assert.match(
    skill,
    /\[port guide\]\(\.\.\/\.\.\/guide\/agent\/app-setup\/existing-application-migration\.md\)/u
  );
  assert.match(distributedGuide, /Generated by `npm run agent-docs:build`/u);

  for (const guide of [sourceGuide, distributedGuide]) {
    assert.match(guide, /Inventory behavior before changing structure/u);
    assert.match(guide, /defineFeature\(\)/u);
    assert.match(guide, /There is no supported\s+`jskit doctor` command/u);
    assert.match(guide, /Audit application `AGENTS\.md` files/u);
    assert.match(guide, /operationLifecycle/u);
    assert.match(guide, /decorateService/u);
    assert.match(guide, /decorateRepository/u);
    assert.match(guide, /Preserve the basename of every applied/u);
    assert.match(guide, /one isolated mutable development database per\s+session/u);
    assert.match(guide, /process umask `0007`/u);
    assert.match(guide, /managed preview identity selects an existing auth-backend user/u);
    assert.match(guide, /patterns as examples, not regeneration input/iu);
    assert.match(guide, /Five finish gates/u);
    assert.match(guide, /Downstream proof: DogAndGroom/u);
    assert.match(guide, /separate Genesis reconciliation and JSKIT\/Material Deslop/u);
    assert.doesNotMatch(guide, /run `?(?:npx )?jskit doctor/iu);
    assert.doesNotMatch(guide, /machine-readable|receipt\.json|completion\.json/u);
  }
});
