/**
 * This file is generated by scripts/framework/generate-db-pack-placeholder-seed.mjs.
 */
exports.seed = async function seed(knex) {
  await knex("jskit_placeholder").del();
  await knex("jskit_placeholder").insert([
    {
      label: "seeded-by-jskit-db-pack"
    }
  ]);
};
