import {
  OWNER_ROLE_ID,
  ADMIN_ROLE_ID,
  MEMBER_ROLE_ID,
  ROLE_CATALOG,
  ASSIGNABLE_ROLE_IDS,
  resolveRolePermissions,
  listRoleDescriptors,
  hasPermission
} from "./roles.js";

import {
  DEFAULT_WORKSPACE_COLOR,
  DEFAULT_USER_SETTINGS,
  coerceWorkspaceColor
} from "./settings.js";
import {
  ACCOUNT_SETTINGS_CHANGED_EVENT,
  CONSOLE_SETTINGS_CHANGED_EVENT,
  WORKSPACE_SETTINGS_CHANGED_EVENT,
  WORKSPACE_MEMBERS_CHANGED_EVENT,
  WORKSPACE_INVITES_CHANGED_EVENT,
  WORKSPACES_CHANGED_EVENT,
  WORKSPACE_PENDING_INVITATIONS_CHANGED_EVENT
} from "./events/usersEvents.js";

const USERS_SHARED_API = Object.freeze({
  OWNER_ROLE_ID,
  ADMIN_ROLE_ID,
  MEMBER_ROLE_ID,
  ROLE_CATALOG,
  ASSIGNABLE_ROLE_IDS,
  resolveRolePermissions,
  listRoleDescriptors,
  hasPermission,
  DEFAULT_WORKSPACE_COLOR,
  DEFAULT_USER_SETTINGS,
  coerceWorkspaceColor,
  ACCOUNT_SETTINGS_CHANGED_EVENT,
  CONSOLE_SETTINGS_CHANGED_EVENT,
  WORKSPACE_SETTINGS_CHANGED_EVENT,
  WORKSPACE_MEMBERS_CHANGED_EVENT,
  WORKSPACE_INVITES_CHANGED_EVENT,
  WORKSPACES_CHANGED_EVENT,
  WORKSPACE_PENDING_INVITATIONS_CHANGED_EVENT
});

export {
  OWNER_ROLE_ID,
  ADMIN_ROLE_ID,
  MEMBER_ROLE_ID,
  ROLE_CATALOG,
  ASSIGNABLE_ROLE_IDS,
  resolveRolePermissions,
  listRoleDescriptors,
  hasPermission,
  DEFAULT_WORKSPACE_COLOR,
  DEFAULT_USER_SETTINGS,
  coerceWorkspaceColor,
  ACCOUNT_SETTINGS_CHANGED_EVENT,
  CONSOLE_SETTINGS_CHANGED_EVENT,
  WORKSPACE_SETTINGS_CHANGED_EVENT,
  WORKSPACE_MEMBERS_CHANGED_EVENT,
  WORKSPACE_INVITES_CHANGED_EVENT,
  WORKSPACES_CHANGED_EVENT,
  WORKSPACE_PENDING_INVITATIONS_CHANGED_EVENT,
  USERS_SHARED_API
};
