import {
  OWNER_ROLE_ID,
  ADMIN_ROLE_ID,
  MEMBER_ROLE_ID,
  resolveRolePermissions,
  listRoleDescriptors,
  hasPermission
} from "./roles.js";

import {
  DEFAULT_WORKSPACE_DARK_PALETTE,
  DEFAULT_WORKSPACE_LIGHT_PALETTE,
  DEFAULT_WORKSPACE_COLOR,
  DEFAULT_USER_SETTINGS,
  coerceWorkspaceColor,
  coerceWorkspaceThemeColor,
  coerceWorkspaceSecondaryColor,
  coerceWorkspaceSurfaceColor,
  coerceWorkspaceSurfaceVariantColor,
  normalizeWorkspaceHexColor,
  normalizeWorkspaceThemeMode,
  resolveWorkspaceThemeDefaultPalette,
  resolveWorkspaceThemePalettes,
  WORKSPACE_THEME_MODE_DARK,
  WORKSPACE_THEME_MODE_LIGHT,
  resolveWorkspaceThemePalette
} from "./settings.js";
import {
  TENANCY_MODE_NONE,
  TENANCY_MODE_PERSONAL,
  TENANCY_MODE_WORKSPACES,
  normalizeTenancyMode,
  WORKSPACE_SLUG_POLICY_NONE,
  WORKSPACE_SLUG_POLICY_IMMUTABLE_USERNAME,
  WORKSPACE_SLUG_POLICY_USER_SELECTED,
  resolveTenancyProfile,
  isWorkspacesTenancyMode
} from "./tenancyProfile.js";

const USERS_SHARED_API = Object.freeze({
  OWNER_ROLE_ID,
  ADMIN_ROLE_ID,
  MEMBER_ROLE_ID,
  resolveRolePermissions,
  listRoleDescriptors,
  hasPermission,
  DEFAULT_WORKSPACE_LIGHT_PALETTE,
  DEFAULT_WORKSPACE_DARK_PALETTE,
  DEFAULT_WORKSPACE_COLOR,
  DEFAULT_USER_SETTINGS,
  coerceWorkspaceColor,
  coerceWorkspaceThemeColor,
  coerceWorkspaceSecondaryColor,
  coerceWorkspaceSurfaceColor,
  coerceWorkspaceSurfaceVariantColor,
  WORKSPACE_THEME_MODE_LIGHT,
  WORKSPACE_THEME_MODE_DARK,
  normalizeWorkspaceThemeMode,
  resolveWorkspaceThemeDefaultPalette,
  resolveWorkspaceThemePalettes,
  normalizeWorkspaceHexColor,
  resolveWorkspaceThemePalette,
  TENANCY_MODE_NONE,
  TENANCY_MODE_PERSONAL,
  TENANCY_MODE_WORKSPACES,
  normalizeTenancyMode,
  WORKSPACE_SLUG_POLICY_NONE,
  WORKSPACE_SLUG_POLICY_IMMUTABLE_USERNAME,
  WORKSPACE_SLUG_POLICY_USER_SELECTED,
  resolveTenancyProfile,
  isWorkspacesTenancyMode
});

export {
  OWNER_ROLE_ID,
  ADMIN_ROLE_ID,
  MEMBER_ROLE_ID,
  resolveRolePermissions,
  listRoleDescriptors,
  hasPermission,
  DEFAULT_WORKSPACE_LIGHT_PALETTE,
  DEFAULT_WORKSPACE_DARK_PALETTE,
  DEFAULT_WORKSPACE_COLOR,
  DEFAULT_USER_SETTINGS,
  coerceWorkspaceColor,
  coerceWorkspaceThemeColor,
  coerceWorkspaceSecondaryColor,
  coerceWorkspaceSurfaceColor,
  coerceWorkspaceSurfaceVariantColor,
  WORKSPACE_THEME_MODE_LIGHT,
  WORKSPACE_THEME_MODE_DARK,
  normalizeWorkspaceThemeMode,
  resolveWorkspaceThemeDefaultPalette,
  resolveWorkspaceThemePalettes,
  normalizeWorkspaceHexColor,
  resolveWorkspaceThemePalette,
  TENANCY_MODE_NONE,
  TENANCY_MODE_PERSONAL,
  TENANCY_MODE_WORKSPACES,
  normalizeTenancyMode,
  WORKSPACE_SLUG_POLICY_NONE,
  WORKSPACE_SLUG_POLICY_IMMUTABLE_USERNAME,
  WORKSPACE_SLUG_POLICY_USER_SELECTED,
  resolveTenancyProfile,
  isWorkspacesTenancyMode,
  USERS_SHARED_API
};
