import {
  OWNER_ROLE_ID,
  ADMIN_ROLE_ID,
  MEMBER_ROLE_ID,
  resolveRolePermissions,
  listRoleDescriptors,
  hasPermission
} from "./roles.js";

import {
  DEFAULT_WORKSPACE_DARK_PALETTE,
  DEFAULT_WORKSPACE_LIGHT_PALETTE,
  DEFAULT_WORKSPACE_COLOR,
  DEFAULT_USER_SETTINGS,
  coerceWorkspaceColor,
  coerceWorkspaceThemeColor,
  coerceWorkspaceSecondaryColor,
  coerceWorkspaceSurfaceColor,
  coerceWorkspaceSurfaceVariantColor,
  normalizeWorkspaceHexColor,
  normalizeWorkspaceThemeMode,
  resolveWorkspaceThemeDefaultPalette,
  resolveWorkspaceThemePalettes,
  WORKSPACE_THEME_MODE_DARK,
  WORKSPACE_THEME_MODE_LIGHT,
  resolveWorkspaceThemePalette
} from "./settings.js";
import {
  TENANCY_MODE_NONE,
  TENANCY_MODE_PERSONAL,
  TENANCY_MODE_WORKSPACE,
  normalizeTenancyMode,
  WORKSPACE_SLUG_POLICY_NONE,
  WORKSPACE_SLUG_POLICY_IMMUTABLE_USERNAME,
  WORKSPACE_SLUG_POLICY_USER_SELECTED,
  resolveTenancyProfile,
  isWorkspaceTenancyMode
} from "./tenancyProfile.js";
import {
  ACCOUNT_SETTINGS_CHANGED_EVENT,
  CONSOLE_SETTINGS_CHANGED_EVENT,
  WORKSPACE_SETTINGS_CHANGED_EVENT,
  WORKSPACE_MEMBERS_CHANGED_EVENT,
  WORKSPACE_INVITES_CHANGED_EVENT,
  WORKSPACES_CHANGED_EVENT,
  WORKSPACE_PENDING_INVITATIONS_CHANGED_EVENT
} from "./events/usersEvents.js";

const USERS_SHARED_API = Object.freeze({
  OWNER_ROLE_ID,
  ADMIN_ROLE_ID,
  MEMBER_ROLE_ID,
  resolveRolePermissions,
  listRoleDescriptors,
  hasPermission,
  DEFAULT_WORKSPACE_LIGHT_PALETTE,
  DEFAULT_WORKSPACE_DARK_PALETTE,
  DEFAULT_WORKSPACE_COLOR,
  DEFAULT_USER_SETTINGS,
  coerceWorkspaceColor,
  coerceWorkspaceThemeColor,
  coerceWorkspaceSecondaryColor,
  coerceWorkspaceSurfaceColor,
  coerceWorkspaceSurfaceVariantColor,
  WORKSPACE_THEME_MODE_LIGHT,
  WORKSPACE_THEME_MODE_DARK,
  normalizeWorkspaceThemeMode,
  resolveWorkspaceThemeDefaultPalette,
  resolveWorkspaceThemePalettes,
  normalizeWorkspaceHexColor,
  resolveWorkspaceThemePalette,
  TENANCY_MODE_NONE,
  TENANCY_MODE_PERSONAL,
  TENANCY_MODE_WORKSPACE,
  normalizeTenancyMode,
  WORKSPACE_SLUG_POLICY_NONE,
  WORKSPACE_SLUG_POLICY_IMMUTABLE_USERNAME,
  WORKSPACE_SLUG_POLICY_USER_SELECTED,
  resolveTenancyProfile,
  isWorkspaceTenancyMode,
  ACCOUNT_SETTINGS_CHANGED_EVENT,
  CONSOLE_SETTINGS_CHANGED_EVENT,
  WORKSPACE_SETTINGS_CHANGED_EVENT,
  WORKSPACE_MEMBERS_CHANGED_EVENT,
  WORKSPACE_INVITES_CHANGED_EVENT,
  WORKSPACES_CHANGED_EVENT,
  WORKSPACE_PENDING_INVITATIONS_CHANGED_EVENT
});

export {
  OWNER_ROLE_ID,
  ADMIN_ROLE_ID,
  MEMBER_ROLE_ID,
  resolveRolePermissions,
  listRoleDescriptors,
  hasPermission,
  DEFAULT_WORKSPACE_LIGHT_PALETTE,
  DEFAULT_WORKSPACE_DARK_PALETTE,
  DEFAULT_WORKSPACE_COLOR,
  DEFAULT_USER_SETTINGS,
  coerceWorkspaceColor,
  coerceWorkspaceThemeColor,
  coerceWorkspaceSecondaryColor,
  coerceWorkspaceSurfaceColor,
  coerceWorkspaceSurfaceVariantColor,
  WORKSPACE_THEME_MODE_LIGHT,
  WORKSPACE_THEME_MODE_DARK,
  normalizeWorkspaceThemeMode,
  resolveWorkspaceThemeDefaultPalette,
  resolveWorkspaceThemePalettes,
  normalizeWorkspaceHexColor,
  resolveWorkspaceThemePalette,
  TENANCY_MODE_NONE,
  TENANCY_MODE_PERSONAL,
  TENANCY_MODE_WORKSPACE,
  normalizeTenancyMode,
  WORKSPACE_SLUG_POLICY_NONE,
  WORKSPACE_SLUG_POLICY_IMMUTABLE_USERNAME,
  WORKSPACE_SLUG_POLICY_USER_SELECTED,
  resolveTenancyProfile,
  isWorkspaceTenancyMode,
  ACCOUNT_SETTINGS_CHANGED_EVENT,
  CONSOLE_SETTINGS_CHANGED_EVENT,
  WORKSPACE_SETTINGS_CHANGED_EVENT,
  WORKSPACE_MEMBERS_CHANGED_EVENT,
  WORKSPACE_INVITES_CHANGED_EVENT,
  WORKSPACES_CHANGED_EVENT,
  WORKSPACE_PENDING_INVITATIONS_CHANGED_EVENT,
  USERS_SHARED_API
};
