storage: ./storage

auth:
  htpasswd:
    file: ./htpasswd

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  "@jskit-ai/*":
    access: $all
    publish: $all
    unpublish: $all

  "**":
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs

log:
  - type: stdout
    format: pretty
    level: http
