import { runAppUpdatePackagesCommand } from "./updatePackages.js";
import {
  formatUtcReleaseTimestamp,
  runExternalCommand
} from "./shared.js";

async function runAppReleaseCommand(ctx = {}, { appRoot = "", options = {}, stdout, stderr }) {
  const { createCliError } = ctx;

  runExternalCommand("gh", ["auth", "status"], {
    cwd: appRoot,
    stdout,
    stderr,
    quiet: true,
    createCliError
  });

  const worktreeStatus = runExternalCommand("git", ["status", "--porcelain"], {
    cwd: appRoot,
    stdout,
    stderr,
    quiet: true,
    createCliError
  });
  if (String(worktreeStatus.stdout || "").trim()) {
    throw createCliError("[release] worktree is not clean. Commit or stash changes first.", {
      exitCode: 1
    });
  }

  const branchResult = runExternalCommand("git", ["rev-parse", "--abbrev-ref", "HEAD"], {
    cwd: appRoot,
    stdout,
    stderr,
    quiet: true,
    createCliError
  });
  const currentBranch = String(branchResult.stdout || "").trim();
  if (currentBranch !== "main") {
    throw createCliError(`[release] current branch is "${currentBranch}". Switch to main first.`, {
      exitCode: 1
    });
  }

  if (options?.dryRun) {
    stdout.write("[release] dry-run mode: would sync main, run jskit app update-packages, and open a PR if changes appear.\n");
    return 0;
  }

  stdout.write("[release] syncing local main...\n");
  runExternalCommand("git", ["fetch", "origin", "main"], {
    cwd: appRoot,
    stdout,
    stderr,
    createCliError
  });
  runExternalCommand("git", ["pull", "--ff-only", "origin", "main"], {
    cwd: appRoot,
    stdout,
    stderr,
    createCliError
  });

  stdout.write("[release] running package refresh...\n");
  const registryUrl = String(options?.inlineOptions?.registry || "").trim();
  await runAppUpdatePackagesCommand(ctx, {
    appRoot,
    options: {
      ...options,
      dryRun: false,
      inlineOptions: registryUrl
        ? { registry: registryUrl }
        : {}
    },
    stdout,
    stderr
  });

  const postUpdateStatus = runExternalCommand("git", ["status", "--porcelain"], {
    cwd: appRoot,
    stdout,
    stderr,
    quiet: true,
    createCliError
  });
  if (!String(postUpdateStatus.stdout || "").trim()) {
    stdout.write("[release] no changes produced by jskit app update-packages. Nothing to release.\n");
    return 0;
  }

  const { branchStamp, pretty } = formatUtcReleaseTimestamp();
  const branchName = `release/${branchStamp}`;
  const commitMessage = `chore: release ${pretty}`;
  const prTitle = `Release ${pretty}`;
  const prBody = "Automated release commit generated by `jskit app release`.";

  stdout.write(`[release] creating branch ${branchName}...\n`);
  runExternalCommand("git", ["switch", "-c", branchName], {
    cwd: appRoot,
    stdout,
    stderr,
    createCliError
  });
  runExternalCommand("git", ["add", "-A"], {
    cwd: appRoot,
    stdout,
    stderr,
    createCliError
  });
  runExternalCommand("git", ["commit", "-m", commitMessage], {
    cwd: appRoot,
    stdout,
    stderr,
    createCliError
  });
  runExternalCommand("git", ["push", "-u", "origin", branchName], {
    cwd: appRoot,
    stdout,
    stderr,
    createCliError
  });

  const prCreateResult = runExternalCommand("gh", [
    "pr",
    "create",
    "--base",
    "main",
    "--head",
    branchName,
    "--title",
    prTitle,
    "--body",
    prBody
  ], {
    cwd: appRoot,
    stdout,
    stderr,
    quiet: true,
    createCliError
  });
  const prUrl = String(prCreateResult.stdout || "").trim();
  if (!prUrl) {
    throw createCliError("[release] gh pr create did not return a PR URL.", {
      exitCode: 1
    });
  }

  stdout.write(`[release] created PR: ${prUrl}\n`);
  runExternalCommand("gh", ["pr", "merge", prUrl, "--merge", "--delete-branch"], {
    cwd: appRoot,
    stdout,
    stderr,
    createCliError
  });

  stdout.write("[release] merged. syncing local main...\n");
  runExternalCommand("git", ["switch", "main"], {
    cwd: appRoot,
    stdout,
    stderr,
    createCliError
  });
  runExternalCommand("git", ["pull", "--ff-only", "origin", "main"], {
    cwd: appRoot,
    stdout,
    stderr,
    createCliError
  });
  stdout.write("[release] done.\n");

  return 0;
}

export { runAppReleaseCommand };
