const USERS_WORKSPACE_PENDING_INVITATIONS_SERVICE_TOKEN = "users.workspace.pending-invitations.service";
const USERS_WORKSPACE_TENANCY_ENABLED_TOKEN = "users.workspace.tenancy.enabled";
const USERS_AVATAR_STORAGE_SERVICE_TOKEN = "users.avatar.storage.service";
const USERS_AVATAR_SERVICE_TOKEN = "users.avatar.service";

export {
  USERS_WORKSPACE_PENDING_INVITATIONS_SERVICE_TOKEN,
  USERS_WORKSPACE_TENANCY_ENABLED_TOKEN,
  USERS_AVATAR_STORAGE_SERVICE_TOKEN,
  USERS_AVATAR_SERVICE_TOKEN
};
