const USERS_WORKSPACE_PENDING_INVITATIONS_SERVICE_TOKEN = "users.workspace.pending-invitations.service";
const USERS_WORKSPACE_ENABLED_TOKEN = "users.workspace.enabled";
const USERS_WORKSPACE_TENANCY_ENABLED_TOKEN = "users.workspace.tenancy.enabled";
const USERS_WORKSPACE_INVITATIONS_ENABLED_TOKEN = "users.workspace.invitations.enabled";
const USERS_WORKSPACE_SELF_CREATE_ENABLED_TOKEN = "users.workspace.self-create.enabled";
const USERS_TENANCY_PROFILE_TOKEN = "users.tenancy.profile";
const USERS_AVATAR_STORAGE_SERVICE_TOKEN = "users.avatar.storage.service";
const USERS_AVATAR_SERVICE_TOKEN = "users.avatar.service";
const USERS_PROFILE_SYNC_SERVICE_TOKEN = "users.profile.sync.service";

export {
  USERS_WORKSPACE_PENDING_INVITATIONS_SERVICE_TOKEN,
  USERS_WORKSPACE_ENABLED_TOKEN,
  USERS_WORKSPACE_TENANCY_ENABLED_TOKEN,
  USERS_WORKSPACE_INVITATIONS_ENABLED_TOKEN,
  USERS_WORKSPACE_SELF_CREATE_ENABLED_TOKEN,
  USERS_TENANCY_PROFILE_TOKEN,
  USERS_AVATAR_STORAGE_SERVICE_TOKEN,
  USERS_AVATAR_SERVICE_TOKEN,
  USERS_PROFILE_SYNC_SERVICE_TOKEN
};
