const USERS_WEB_BOOTSTRAP_PLACEMENT_RUNTIME_TOKEN = "users.web.bootstrap-placement.runtime";
const BOOTSTRAP_PLACEMENT_SOURCE = "users-web.bootstrap-placement";
const WORKSPACE_BOOTSTRAP_STATUS_RESOLVED = "resolved";
const WORKSPACE_BOOTSTRAP_STATUS_NOT_FOUND = "not_found";
const WORKSPACE_BOOTSTRAP_STATUS_FORBIDDEN = "forbidden";
const WORKSPACE_BOOTSTRAP_STATUS_UNAUTHENTICATED = "unauthenticated";
const WORKSPACE_BOOTSTRAP_STATUS_ERROR = "error";
const SHELL_GUARD_EVALUATOR_KEY = "__JSKIT_WEB_SHELL_GUARD_EVALUATOR__";
const WORKSPACE_NOT_FOUND_GUARD_REASON = "workspace-not-found";
const WORKSPACE_FORBIDDEN_GUARD_REASON = "workspace-forbidden";

const WORKSPACE_BOOTSTRAP_STATUSES = new Set([
  WORKSPACE_BOOTSTRAP_STATUS_RESOLVED,
  WORKSPACE_BOOTSTRAP_STATUS_NOT_FOUND,
  WORKSPACE_BOOTSTRAP_STATUS_FORBIDDEN,
  WORKSPACE_BOOTSTRAP_STATUS_UNAUTHENTICATED,
  WORKSPACE_BOOTSTRAP_STATUS_ERROR
]);

export {
  BOOTSTRAP_PLACEMENT_SOURCE,
  SHELL_GUARD_EVALUATOR_KEY,
  USERS_WEB_BOOTSTRAP_PLACEMENT_RUNTIME_TOKEN,
  WORKSPACE_BOOTSTRAP_STATUSES,
  WORKSPACE_BOOTSTRAP_STATUS_ERROR,
  WORKSPACE_BOOTSTRAP_STATUS_FORBIDDEN,
  WORKSPACE_BOOTSTRAP_STATUS_NOT_FOUND,
  WORKSPACE_BOOTSTRAP_STATUS_RESOLVED,
  WORKSPACE_BOOTSTRAP_STATUS_UNAUTHENTICATED,
  WORKSPACE_FORBIDDEN_GUARD_REASON,
  WORKSPACE_NOT_FOUND_GUARD_REASON
};
