<script setup>
const title = "App Home";
</script>

<template>
  <section>
    <h1>{{ title }}</h1>
    <p>This is the default app surface page generated by the web-shell scaffold.</p>
  </section>
</template>
